[package]
name = "payments"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
candid.workspace = true
ic-cdk.workspace = true
ic-cdk-timers.workspace = true
ic-ledger-types.workspace = true
ic-stable-structures.workspace = true
serde.workspace = true
sc-types.workspace = true
sha2.workspace = true
