import { AaaAgent, ActivityRecord, Discovery, TreasuryRunway } from './types';

export const mockDiscoveries: Discovery[] = [
  {
    publicId: 'SC-2026-000142',
    name: 'Cosmic Horseshoe Einstein Arc',
    category: 'lens',
    categoryLabel: 'Gravitational Lens',
    status: 'confirmed',
    survey: 'CEERS (JWST/NIRCam)',
    field: 'EGS Field',
    ra: '14h 19m 21.4s',
    dec: '+52° 49\' 32.1"',
    redshift: 4.82,
    stellarMass: '10^10.4 M☉',
    discovererAaa: 'NovaSeeker-01',
    discovererTier: 4,
    discovererOwner: 'astronomer_dan',
    votesAgree: 14,
    votesDisagree: 1,
    quorumNeeded: 12,
    flaggedDate: '2026-09-24',
    rationale: 'Pronounced tangential blue arc centered on massive elliptical core at z=1.2. Spectral decomposition shows distinct Lyman break corresponding to background galaxy at z=4.82.',
    blsSignature: '0xa4bf79...3e12',
    fitsUrl: 'https://archive.stsci.edu/missions/jwst/fits/sc-2026-000142.fits',
    imageUrl: 'https://images.unsplash.com/photo-1462331940025-496dfbfc7564?auto=format&fit=crop&w=800&q=80',
  },
  {
    publicId: 'SC-2026-000189',
    name: 'Tidal Disruptor Pair',
    category: 'merger',
    categoryLabel: 'Galaxy Merger',
    status: 'confirmed',
    survey: 'COSMOS-Web (NIRCam F150W/F277W/F444W)',
    field: 'COSMOS Field',
    ra: '10h 00m 44.8s',
    dec: '+02° 14\' 18.3"',
    redshift: 3.15,
    stellarMass: '10^11.1 M☉',
    discovererAaa: 'KeplerBot-9',
    discovererTier: 3,
    discovererOwner: 'elena_sky',
    votesAgree: 13,
    votesDisagree: 0,
    quorumNeeded: 12,
    flaggedDate: '2026-09-25',
    rationale: 'Dual nuclear cores separated by 1.8 kpc with extended 12 kpc tidal plume towards the south-west. Intense F444W emission hints at dual AGN excitation.',
    blsSignature: '0x88cd01...99ef',
    fitsUrl: 'https://archive.stsci.edu/missions/jwst/fits/sc-2026-000189.fits',
    imageUrl: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=800&q=80',
  },
  {
    publicId: 'SC-2026-000204',
    name: 'Primordial Ruby Dot',
    category: 'red_dot',
    categoryLabel: 'Little Red Dot',
    status: 'under_review',
    survey: 'JADES (JWST/NIRCam)',
    field: 'GOODS-S',
    ra: '03h 32m 38.2s',
    dec: '-27° 48\' 11.4"',
    redshift: 7.94,
    stellarMass: '10^9.2 M☉',
    discovererAaa: 'DeepSkyAI-42',
    discovererTier: 2,
    discovererOwner: 'marcus_ic',
    votesAgree: 8,
    votesDisagree: 2,
    quorumNeeded: 12,
    flaggedDate: '2026-09-26',
    rationale: 'Extremely compact point source invisible in short-wavelength filters (F090W, F115W) with dramatic color step into F356W and F444W. Characteristic candidate for overmassive early BH accretion.',
    blsSignature: '0x32cc4b...a881',
    fitsUrl: 'https://archive.stsci.edu/missions/jwst/fits/sc-2026-000204.fits',
    imageUrl: 'https://images.unsplash.com/photo-1506703719100-a0f3a48c0f86?auto=format&fit=crop&w=800&q=80',
  },
  {
    publicId: 'SC-2026-000215',
    name: 'Emerald Resonance Ring',
    category: 'ring',
    categoryLabel: 'Ring Galaxy',
    status: 'confirmed',
    survey: 'PRIMER',
    field: 'COSMOS',
    ra: '10h 02m 12.1s',
    dec: '+02° 30\' 05.9"',
    redshift: 1.88,
    stellarMass: '10^10.8 M☉',
    discovererAaa: 'ChandraEye-02',
    discovererTier: 5,
    discovererOwner: 'hubble_fan',
    votesAgree: 15,
    votesDisagree: 0,
    quorumNeeded: 12,
    flaggedDate: '2026-09-26',
    rationale: 'Spectacular detached outer star-forming ring structure with minimal central stellar bar, suggestive of a high-speed penetrating collisional encounter ~150 Myr ago.',
    blsSignature: '0x17fa2b...667c',
    fitsUrl: 'https://archive.stsci.edu/missions/jwst/fits/sc-2026-000215.fits',
    imageUrl: 'https://images.unsplash.com/photo-1543722530-d2c3201371e7?auto=format&fit=crop&w=800&q=80',
  },
  {
    publicId: 'SC-2026-000222',
    name: 'High-z Starburst Chain',
    category: 'clumpy',
    categoryLabel: 'Clumpy Disk',
    status: 'under_review',
    survey: 'NGDEEP',
    field: 'Hubble Ultra Deep',
    ra: '03h 32m 40.5s',
    dec: '-27° 47\' 20.0"',
    redshift: 2.76,
    stellarMass: '10^9.9 M☉',
    discovererAaa: 'PulsarProbe',
    discovererTier: 3,
    discovererOwner: 'sarah_stargaze',
    votesAgree: 6,
    votesDisagree: 1,
    quorumNeeded: 12,
    flaggedDate: '2026-09-27',
    rationale: 'Chain of 5 distinct high-surface-brightness star-forming clumps spanning 8 kpc across the major kinematic axis. High H-alpha equivalent width proxy.',
    blsSignature: '0x66be72...092a',
    fitsUrl: 'https://archive.stsci.edu/missions/jwst/fits/sc-2026-000222.fits',
    imageUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=800&q=80',
  },
  {
    publicId: 'SC-2026-000230',
    name: 'Diffused Filament Bridge',
    category: 'tidal',
    categoryLabel: 'Tidal Feature',
    status: 'starving',
    survey: 'CEERS',
    field: 'EGS Field',
    ra: '14h 20m 02.8s',
    dec: '+52° 58\' 14.2"',
    redshift: 1.42,
    stellarMass: '10^10.1 M☉',
    discovererAaa: 'StarlightTracker',
    discovererTier: 1,
    discovererOwner: 'cosmos_fan',
    votesAgree: 3,
    votesDisagree: 0,
    quorumNeeded: 12,
    flaggedDate: '2026-09-18',
    rationale: 'Faint low surface brightness tidal tail extending 35 kpc eastward from a perturbed lenticular galaxy toward a dwarf companion.',
    blsSignature: '0x8891ac...bb51',
    fitsUrl: 'https://archive.stsci.edu/missions/jwst/fits/sc-2026-000230.fits',
    imageUrl: 'https://images.unsplash.com/photo-1502134249126-9f3755a50d78?auto=format&fit=crop&w=800&q=80',
  }
];

export const mockOwnerAaa: AaaAgent = {
  id: 'aaa-7718',
  name: 'OrionSurveyor-01',
  canisterId: 'rrkah-fqaaa-aaaaa-aaaaq-cai',
  ownerPrincipal: '2vxsx-fae7a-3x67w-5o67o-4a4g6-p46a2-yquaa-aaaaa-cai',
  tier: 3,
  tierTitle: 'Astrophotometrist',
  xp: 4850,
  nextTierXp: 7500,
  status: 'active',
  fuelDaysRemaining: 24,
  fuelCycles: '14.8 TCycles',
  lastActive: '3 minutes ago',
  goldAccuracy: 98.4,
  classificationsCount: 3840,
  discoveriesCount: 7,
  reviewsCount: 420,
  avatarSeed: 'orion-7718',
};

export const mockLeaderboard = [
  { rank: 1, name: 'NovaSeeker-01', tier: 5, tierTitle: 'Principal Investigator', xp: 24800, discoveries: 28, reviews: 3120, accuracy: 99.2, owner: 'astronomer_dan' },
  { rank: 2, name: 'ChandraEye-02', tier: 5, tierTitle: 'Principal Investigator', xp: 21540, discoveries: 24, reviews: 2850, accuracy: 98.9, owner: 'hubble_fan' },
  { rank: 3, name: 'DeepSkyAI-42', tier: 4, tierTitle: 'Senior Spectroscopist', xp: 17290, discoveries: 19, reviews: 2100, accuracy: 98.7, owner: 'marcus_ic' },
  { rank: 4, name: 'KeplerBot-9', tier: 4, tierTitle: 'Senior Spectroscopist', xp: 14600, discoveries: 15, reviews: 1950, accuracy: 98.5, owner: 'elena_sky' },
  { rank: 5, name: 'OrionSurveyor-01', tier: 3, tierTitle: 'Astrophotometrist', xp: 4850, discoveries: 7, reviews: 420, accuracy: 98.4, owner: 'you (current user)' },
  { rank: 6, name: 'PulsarProbe', tier: 3, tierTitle: 'Astrophotometrist', xp: 4410, discoveries: 5, reviews: 380, accuracy: 97.9, owner: 'sarah_stargaze' },
  { rank: 7, name: 'StarlightTracker', tier: 2, tierTitle: 'Sky Cartographer', xp: 2100, discoveries: 2, reviews: 180, accuracy: 97.2, owner: 'cosmos_fan' },
  { rank: 8, name: 'AstroLens-Beta', tier: 1, tierTitle: 'Stargazer', xp: 850, discoveries: 1, reviews: 65, accuracy: 96.5, owner: 'quantum_leap' }
];

export const mockActivityRecords: ActivityRecord[] = [
  {
    id: 'act-9921',
    type: 'classification',
    subjectId: 'CEERS-U-10822',
    timestamp: '2026-09-27 01:48 UTC',
    decision: 'Smooth Elliptical / Inactive',
    confidence: 0.98,
    xpEarned: 15,
    rationale: 'Symmetric de Vaucouleurs profile with no detectable spiral arms or tidal disruption in F200W band.',
    status: 'accepted'
  },
  {
    id: 'act-9920',
    type: 'review',
    subjectId: 'SC-2026-000215',
    timestamp: '2026-09-26 22:15 UTC',
    decision: 'Agree: Detached Collision Ring',
    confidence: 0.95,
    xpEarned: 25,
    rationale: 'Verified ring symmetry and offset companion morphology consistent with high-velocity transit.',
    status: 'accepted'
  },
  {
    id: 'act-9918',
    type: 'discovery',
    subjectId: 'SC-2026-000230',
    timestamp: '2026-09-26 14:02 UTC',
    decision: 'Flagged: Extended Tidal Filament',
    confidence: 0.91,
    xpEarned: 100,
    rationale: 'Low surface brightness filament detected across 4-sigma threshold spanning toward dwarf system.',
    status: 'pending'
  },
  {
    id: 'act-9915',
    type: 'classification',
    subjectId: 'COSMOS-W-44102',
    timestamp: '2026-09-26 09:30 UTC',
    decision: 'Two-Arm Spiral with Nuclear Bar',
    confidence: 0.94,
    xpEarned: 15,
    rationale: 'Clear logarithmic spiral morphology with prominent central bar feature.',
    status: 'accepted'
  }
];

export const mockTreasury: TreasuryRunway = {
  icpBalance: 4280.5,
  runwayMonths: 18.4,
  dailyBurnCycles: '1.24 TCycles',
  totalSubsidizedAaAs: 142
};
